### ISSUE TITLE
Feedback on package and feature request on extracting Lats and Lons information from grib2

### ISSUE THREAD

**Issue by wxguy** [noaa-nws-cpc/cpc.geogrids#4]
Hi,
Today, I was about to write a grib2 plot script for plotting NCEP GFS grib2 file for certain parameters usinf wgrib2. However, I was pleasantly surprised to see the quality of package with minimal code. It was extremely useful for learning.Thanks for that. There are certain issues and observation regarding your packages(s) I would like to bring it to your notice (this is valid for all packages). Hope that you would take this as constructive feedback. Here you go:-

1.  The documentation site [https://mikecharles.github.io/cpc.geogrids/](https://mikecharles.github.io/cpc.geogrids/) is off. Please redirect to actual documentation site [https://noaa-nws-cpc.github.io/cpc.geofiles/](https://noaa-nws-cpc.github.io/cpc.geofiles/).

2.  The geogrid package can easily extract the data of given variable from grib2 file. However, the lat/ lon data extraction is missing in the package. Under `pygrib` this is easily done using this command `lat,lon = grb.latlons() `  This would make the like much easier for the users. Right now I use this command `wgrib2 -grid -d 1 /path/to/file.grib2 -no_header -spread -` in the script to loop through each line and extract lat and lon data (then grid using Geogrid). It cost lot of time. 

3.  Why do you really need three different packages? Why don't you have single package with all three feature (geofiles, geogrid and geoplot)?

4.  The package is not installed properly when installed using pip. 

What do you think of the above issues?

**Comment by mikecharles** [comment]
Hi @wxguy !

Thanks for your feedback. I'll answer your questions inline:

> The documentation site https://mikecharles.github.io/cpc.geogrids/ is off. Please redirect to actual documentation site https://noaa-nws-cpc.github.io/cpc.geofiles/.

I moved this package under the @noaa-nws-cpc org a few days ago, because NOAA recently sanctioned using GitHub.com, so some things will need to be changed from @mikecharles to @noaa-nws-cpc in the near future. I will do that soon.

> The geogrid package can easily extract the data of given variable from grib2 file. However, the lat/ lon data extraction is missing in the package. Under pygrib this is easily done using this command lat,lon = grb.latlons() This would make the like much easier for the users. Right now I use this command wgrib2 -grid -d 1 /path/to/file.grib2 -no_header -spread - in the script to loop through each line and extract lat and lon data (then grid using Geogrid). It cost lot of time.

Do you just want the list of lats and lons for a particular grid? If so, you can get that like this:

```python
from cpc.geogrids import Geogrid

geogrid = Geogrid('1deg-global')
print(geogrid.lats)
print(geogrid.lons)
```

> Why do you really need three different packages? Why don't you have single package with all three feature (geofiles, geogrid and geoplot)?

I thought about this, but I realized that (at least us at CPC) each package could have its own specific usage without necessarily using the features of the other packages. I may want to just load data without plotting, or do operations on a grid without actually loading or plotting any data, etc.

Also, as I've become more familiar with Python development, it's served me best to separate out functionality when possible, so I decided on separating the packages.

> The package is not installed properly when installed using pip.

Can you please provide me an example or some error output?

Thanks very much for the feedback!

**Comment by wxguy** [comment]
Thanks for the quick reply.

Extremely sorry for reporting false issue. Pip install works fine. Issued this wrong command:-
`import Geogrid`
instead of this correct one:-
`from cpc.geogrids import Geogrid`

Regarding grib2 file processing, do you have any other plan for inclusion of new features such as listing parameter varables, levels of variales etc.?

Is it not possible to use cpc directory as a package so as to use it without installing?

Will report back issues/ suggestions as and when it occurs at my end.

**Comment by mikecharles** [comment]
> Regarding grib2 file processing, do you have any other plan for inclusion of new features such as listing parameter varables, levels of variales etc.?

I would be fine adding features like this as time permits. Also, I would welcome Pull Requests.

> Is it not possible to use cpc directory as a package so as to use it without installing?

You mean if you were to clone the repo? What do you mean exactly?

> Will report back issues/ suggestions as and when it occurs at my end.

Thanks a lot!

**Comment by wxguy** [comment]
```
from cpc.geogrids import Geogrid

geogrid = Geogrid('1deg-global')
print(geogrid.lats)
print(geogrid.lons)
```

The above code olny lists the lats and lons as list. However, the output of wgrib2 command `wgrib2 -grid -d 1 /path/to/file.grib2 -no_header -spread -` is (259920,). The dimension of lat, lon and data is same for 0.5 deg grib2 data. Can you point me in direct direction.

Regarding the package issue, I would like to keep your geogrid package/ directory next to my script and import directly from main script.

**Comment by mikecharles** [comment]
> The above code olny lists the lats and lons as list. However, the output of wgrib2 command wgrib2 -grid -d 1 /path/to/file.grib2 -no_header -spread - is (259920,). The dimension of lat, lon and data is same for 0.5 deg grib2 data. Can you point me in direct direction.

I see. That would be easy to add. Feel free to create another issue for this and I'll try to get to it soon.

> Regarding the package issue, I would like to keep your geogrid package/ directory next to my script and import directly from main script.

I was able to do this just now:

```
$ git clone git@github.com:noaa-nws-cpc/cpc.geogrids.git
$ cd cpc.geogrids
$ python -c "import cpc.geogrids"
```

As long as you put your script into the `cpc.geogrids` directory it'll work. Also, you can run your script from anywhere if you set the `$PYTHONPATH` variable to include the `cpc.geogrids` directory. For example:

```
$ git clone git@github.com:noaa-nws-cpc/cpc.geogrids.git ~/cpc.geogrids
$ PYTHONPATH=$PYTHONPATH:$HOME/cpc.geogrids python -c "import cpc.geogrids"
```

Or permanently add cpc.geogrids to your `$PYTHONPATH` variable in your `~/.bashrc` file.

**Comment by wxguy** [comment]
Thanks I will open a new one.
